<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Dogeometric.Solids</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dogeometric.Core/Dogeometric.Core.csproj" />
  </ItemGroup>
</Project>
