using System.Text.Json;
using Godot;
using FileAccess = Godot.FileAccess;

namespace Dogeometric.App.Commands;

public sealed class Command(int id)
{
    public int Id { get; } = id;

    /// <summary>Menu label (without the ampersand mnemonic), used for toolbar tooltips.</summary>
    public string Label { get; set; } = "";

    public string Description { get; set; } = "";
    public Action? Execute { get; set; }
    public Func<bool>? IsChecked { get; set; }
    public bool IsRadio { get; set; }

    /// <summary>Default shortcut shown in menus; extra shortcuts live in <see cref="CommandRegistry.Aliases"/>.</summary>
    public Key Shortcut { get; set; } = Key.None;

    /// <summary>Where the command sits in the menus, e.g. "Camera/Zoom" (how SketchUp lists shortcuts).</summary>
    public string MenuPath { get; set; } = "";

    public bool IsImplemented => Execute != null;
}

public sealed record MenuNode(string Label, int? Id, IReadOnlyList<MenuNode>? Children, bool IsSeparator);

/// <summary>
/// SketchUp's commands, menus and default shortcuts, loaded from data/sketchup_commands.json
/// (generated by research/generate_commands.py). Behaviour is attached with <see cref="Register"/>.
/// </summary>
public sealed class CommandRegistry
{
    private readonly Dictionary<int, Command> _commands = [];
    private readonly List<(Key Keys, int Id)> _aliases = [];

    public IReadOnlyList<MenuNode> Menus { get; }
    public IReadOnlyList<(Key Keys, int Id)> Aliases => _aliases;

    public CommandRegistry(string jsonPath)
    {
        using var file = FileAccess.Open(jsonPath, FileAccess.ModeFlags.Read)
            ?? throw new InvalidOperationException($"Cannot open {jsonPath}: {FileAccess.GetOpenError()}");
        using var doc = JsonDocument.Parse(file.GetAsText());
        var root = doc.RootElement;

        foreach (var prop in root.GetProperty("commands").EnumerateObject())
            Get(int.Parse(prop.Name)).Description = prop.Value.GetProperty("description").GetString() ?? "";

        foreach (var s in root.GetProperty("shortcuts").EnumerateArray())
        {
            var keys = ParseKeys(s.GetProperty("keys").GetString()!);
            var cmd = Get(s.GetProperty("id").GetInt32());
            if (cmd.Shortcut == Key.None)
                cmd.Shortcut = keys;
            else
                _aliases.Add((keys, cmd.Id));
        }

        Menus = ParseMenus(root.GetProperty("menus"), "");
    }

    /// <summary>Every command with a label (for Preferences › Shortcuts).</summary>
    public IEnumerable<Command> All => _commands.Values.Where(c => c.Label.Length > 0);

    private const string UserShortcutsPath = "user://shortcuts.json";

    /// <summary>
    /// Gives <paramref name="id"/> the shortcut <paramref name="keys"/> (Key.None removes it). A shortcut belongs to one
    /// command at a time, so other commands and aliases using the same keys lose them.
    /// </summary>
    public void SetShortcut(int id, Key keys)
    {
        if (keys != Key.None)
        {
            foreach (var c in _commands.Values.Where(c => c.Shortcut == keys))
                c.Shortcut = Key.None;
            _aliases.RemoveAll(a => a.Keys == keys);
        }
        Get(id).Shortcut = keys;
    }

    /// <summary>Saves every command's shortcut as the user's choice (SketchUp keeps them in its preferences).</summary>
    public void SaveUserShortcuts()
    {
        // Godot key codes (with modifier bits): exact round trip, unlike display text.
        var map = _commands.Values.Where(c => c.Label.Length > 0).ToDictionary(c => c.Id.ToString(), c => (long)c.Shortcut);
        using var file = FileAccess.Open(UserShortcutsPath, FileAccess.ModeFlags.Write);
        file?.StoreString(JsonSerializer.Serialize(map));
    }

    /// <summary>Applies the user's saved shortcuts over SketchUp's defaults.</summary>
    public void LoadUserShortcuts()
    {
        if (!FileAccess.FileExists(UserShortcutsPath))
            return;
        using var file = FileAccess.Open(UserShortcutsPath, FileAccess.ModeFlags.Read);
        if (file == null)
            return;
        try
        {
            var map = JsonSerializer.Deserialize<Dictionary<string, long>>(file.GetAsText()) ?? [];
            foreach (var c in _commands.Values)
                c.Shortcut = Key.None;
            foreach (var (id, keys) in map)
                if (int.TryParse(id, out var n))
                    Get(n).Shortcut = (Key)keys;
            // SketchUp's secondary shortcuts stay unless the user gave those keys to a command.
            var taken = _commands.Values.Select(c => c.Shortcut).Where(k => k != Key.None).ToHashSet();
            _aliases.RemoveAll(a => taken.Contains(a.Keys));
        }
        catch (JsonException)
        {
        }
    }

    public Command Get(int id)
    {
        if (!_commands.TryGetValue(id, out var cmd))
            _commands[id] = cmd = new Command(id);
        return cmd;
    }

    public void Register(int id, Action execute, Func<bool>? isChecked = null, bool radio = false)
    {
        var cmd = Get(id);
        cmd.Execute = execute;
        cmd.IsChecked = isChecked;
        cmd.IsRadio = radio;
    }

    public bool Execute(int id)
    {
        if (!_commands.TryGetValue(id, out var cmd) || cmd.Execute == null)
            return false;
        cmd.Execute();
        return true;
    }

    private List<MenuNode> ParseMenus(JsonElement items, string path)
    {
        var list = new List<MenuNode>();
        foreach (var it in items.EnumerateArray())
        {
            if (it.TryGetProperty("separator", out _))
            {
                list.Add(new MenuNode("", null, null, true));
                continue;
            }
            var label = it.GetProperty("label").GetString() ?? "";
            var clean = label.Replace("&", "").Replace("...", "").Split('\t')[0];
            if (it.TryGetProperty("children", out var children))
                list.Add(new MenuNode(label, null, ParseMenus(children, path.Length == 0 ? clean : $"{path}/{clean}"), false));
            else
            {
                var id = it.GetProperty("id").GetInt32();
                list.Add(new MenuNode(label, id, null, false));
                var cmd = Get(id);
                if (cmd.Label.Length == 0)
                    cmd.Label = label;
                if (cmd.MenuPath.Length == 0)
                    cmd.MenuPath = path.Length == 0 ? clean : $"{path}/{clean}";
            }
        }
        return list;
    }

    /// <summary>Human-readable shortcut, e.g. "Ctrl+Shift+E".</summary>
    public static string ShortcutText(Key keys) => keys == Key.None ? "" : OS.GetKeycodeString(keys);

    /// <summary>Parses accelerator text such as "Ctrl+Shift+E", "PgDn", "Space" or "F1".</summary>
    public static Key ParseKeys(string text)
    {
        var result = Key.None;
        foreach (var part in text.Split('+'))
        {
            result |= part switch
            {
                "Ctrl" => (Key)KeyModifierMask.MaskCtrl,
                "Shift" => (Key)KeyModifierMask.MaskShift,
                "Alt" => (Key)KeyModifierMask.MaskAlt,
                "Space" => Key.Space,
                "Delete" => Key.Delete,
                "Insert" => Key.Insert,
                "Backspace" => Key.Backspace,
                "PgUp" => Key.Pageup,
                "PgDn" => Key.Pagedown,
                "Enter" => Key.Enter,
                "Esc" => Key.Escape,
                _ when part.Length > 1 && part[0] == 'F' && int.TryParse(part[1..], out var n) => Key.F1 + (n - 1),
                _ when part.Length == 1 && char.IsLetterOrDigit(part[0]) => (Key)char.ToUpperInvariant(part[0]),
                _ => Key.None,
            };
        }
        return result;
    }
}
