using System.Text.Json;
using Godot;
using FileAccess = Godot.FileAccess;

namespace Dogeometric.App.Commands;

public sealed class Command(int id)
{
    public int Id { get; } = id;

    /// <summary>Menu label (without the ampersand mnemonic), used for toolbar tooltips.</summary>
    public string Label { get; set; } = "";

    public string Description { get; set; } = "";
    public Action? Execute { get; set; }
    public Func<bool>? IsChecked { get; set; }
    public bool IsRadio { get; set; }

    /// <summary>Default shortcut shown in menus; extra shortcuts live in <see cref="CommandRegistry.Aliases"/>.</summary>
    public Key Shortcut { get; set; } = Key.None;

    /// <summary>Where the command sits in the menus, e.g. "Camera/Zoom" (how SketchUp lists shortcuts).</summary>
    public string MenuPath { get; set; } = "";

    public bool IsImplemented => Execute != null;
}

public sealed record MenuNode(string Label, int? Id, IReadOnlyList<MenuNode>? Children, bool IsSeparator);

/// <summary>An item a menu lists when it opens; <paramref name="Checked"/> makes it a check item.</summary>
public sealed record DynamicItem(string Label, Action Run, bool? Checked = null);

/// <summary>
/// SketchUp's commands, menus and default shortcuts, loaded from data/sketchup_commands.json
/// (generated by research/generate_commands.py). Behaviour is attached with <see cref="Register"/>.
/// </summary>
public sealed class CommandRegistry
{
    private readonly Dictionary<int, Command> _commands = [];
    private readonly List<(Key Keys, int Id)> _aliases = [];

    public IReadOnlyList<MenuNode> Menus => _menus;
    private readonly List<MenuNode> _menus;
    private readonly List<MenuNode> _native;
    public IReadOnlyList<(Key Keys, int Id)> Aliases => _aliases;

    public CommandRegistry(string jsonPath)
    {
        using var file = FileAccess.Open(jsonPath, FileAccess.ModeFlags.Read)
            ?? throw new InvalidOperationException($"Cannot open {jsonPath}: {FileAccess.GetOpenError()}");
        using var doc = JsonDocument.Parse(file.GetAsText());
        var root = doc.RootElement;

        foreach (var prop in root.GetProperty("commands").EnumerateObject())
            Get(int.Parse(prop.Name)).Description = prop.Value.GetProperty("description").GetString() ?? "";

        foreach (var s in root.GetProperty("shortcuts").EnumerateArray())
        {
            var keys = ParseKeys(s.GetProperty("keys").GetString()!);
            var cmd = Get(s.GetProperty("id").GetInt32());
            if (cmd.Shortcut == Key.None)
                cmd.Shortcut = keys;
            else
                _aliases.Add((keys, cmd.Id));
        }

        _menus = ParseMenus(root.GetProperty("menus"), "");
        _native = [.. _menus];
        RememberDefaults();
    }

    private Dictionary<int, Key> _defaultShortcuts = [];
    private List<(Key Keys, int Id)> _defaultAliases = [];

    private void RememberDefaults()
    {
        _defaultShortcuts = _commands.Values.Where(c => c.Shortcut != Key.None).ToDictionary(c => c.Id, c => c.Shortcut);
        _defaultAliases = [.. _aliases];
    }

    /// <summary>A default shortcut beyond SketchUp's resource tables, kept by Reset All; ignored if the keys are taken.</summary>
    public void AddDefaultShortcut(string keys, int id)
    {
        var k = ParseKeys(keys);
        if (_commands.Values.Any(c => c.Shortcut == k) || _aliases.Any(a => a.Keys == k))
            return;
        if (Get(id).Shortcut == Key.None)
            Get(id).Shortcut = k;
        else
            _aliases.Add((k, id));
        RememberDefaults();
    }

    /// <summary>Preferences › Shortcuts › Reset All: SketchUp's default shortcuts again, for this and later sessions.</summary>
    public void ResetShortcuts()
    {
        foreach (var c in _commands.Values)
            c.Shortcut = _defaultShortcuts.GetValueOrDefault(c.Id, Key.None);
        _aliases.Clear();
        _aliases.AddRange(_defaultAliases);
        if (FileAccess.FileExists(UserShortcutsPath))
            DirAccess.RemoveAbsolute(ProjectSettings.GlobalizePath(UserShortcutsPath));
    }

    /// <summary>Every key binding in force: each command's shortcut and the extra keys that also run it.</summary>
    public IEnumerable<(Key Keys, int Id)> Shortcuts() =>
        _commands.Values.Where(c => c.Shortcut != Key.None).Select(c => (c.Shortcut, c.Id)).Concat(_aliases);

    /// <summary>Every command with a label (for Preferences › Shortcuts).</summary>
    public IEnumerable<Command> All => _commands.Values.Where(c => c.Label.Length > 0);

    private const string UserShortcutsPath = "user://shortcuts.json";

    /// <summary>
    /// Gives <paramref name="id"/> the shortcut <paramref name="keys"/> (Key.None removes it). A shortcut belongs to one
    /// command at a time, so other commands and aliases using the same keys lose them.
    /// </summary>
    public void SetShortcut(int id, Key keys)
    {
        if (keys != Key.None)
        {
            foreach (var c in _commands.Values.Where(c => c.Shortcut == keys))
                c.Shortcut = Key.None;
            _aliases.RemoveAll(a => a.Keys == keys);
        }
        Get(id).Shortcut = keys;
    }

    /// <summary>Saves every command's shortcut as the user's choice (SketchUp keeps them in its preferences).</summary>
    public void SaveUserShortcuts()
    {
        // Godot key codes (with modifier bits): exact round trip, unlike display text.
        var map = _commands.Values.Where(c => c.Label.Length > 0).ToDictionary(c => c.Id.ToString(), c => (long)c.Shortcut);
        using var file = FileAccess.Open(UserShortcutsPath, FileAccess.ModeFlags.Write);
        file?.StoreString(JsonSerializer.Serialize(map));
    }

    /// <summary>Applies the user's saved shortcuts over SketchUp's defaults.</summary>
    public void LoadUserShortcuts()
    {
        if (!FileAccess.FileExists(UserShortcutsPath))
            return;
        using var file = FileAccess.Open(UserShortcutsPath, FileAccess.ModeFlags.Read);
        if (file == null)
            return;
        try
        {
            var map = JsonSerializer.Deserialize<Dictionary<string, long>>(file.GetAsText()) ?? [];
            foreach (var c in _commands.Values)
                c.Shortcut = Key.None;
            foreach (var (id, keys) in map)
                if (int.TryParse(id, out var n))
                    Get(n).Shortcut = (Key)keys;
            // SketchUp's secondary shortcuts stay unless the user gave those keys to a command.
            var taken = _commands.Values.Select(c => c.Shortcut).Where(k => k != Key.None).ToHashSet();
            _aliases.RemoveAll(a => taken.Contains(a.Keys));
        }
        catch (JsonException)
        {
        }
    }

    public Command Get(int id)
    {
        if (!_commands.TryGetValue(id, out var cmd))
            _commands[id] = cmd = new Command(id);
        return cmd;
    }

    /// <summary>
    /// Sets what extensions add to <paramref name="menu"/>: SketchUp's own items followed by <paramref name="spec"/>,
    /// written as SketchUp lists them (two spaces per level, "---" separators, "Label | id" items, bare labels for submenus).
    /// </summary>
    public void SetExtensionMenu(string menu, string spec)
    {
        var index = _menus.FindIndex(m => m.Label.Replace("&", "") == menu);
        if (index < 0)
            return;
        var lines = spec.Replace("\r", "").Split('\n').Where(l => l.Trim().Length > 0).ToList();
        var at = 0;
        List<MenuNode> Parse(int depth, string path)
        {
            var nodes = new List<MenuNode>();
            while (at < lines.Count)
            {
                var line = lines[at];
                var indent = (line.Length - line.TrimStart().Length) / 2;
                if (indent < depth)
                    break;
                at++;
                var text = line.Trim();
                if (text == "---")
                    nodes.Add(new MenuNode("", null, null, true));
                else if (text.LastIndexOf(" | ", StringComparison.Ordinal) is var bar and >= 0)
                {
                    var (label, id) = (text[..bar], int.Parse(text[(bar + 3)..]));
                    nodes.Add(new MenuNode(label, id, null, false));
                    Get(id).Label = label;
                    Get(id).MenuPath = $"{path}/{label}";
                }
                else
                    nodes.Add(new MenuNode(text, null, Parse(depth + 1, $"{path}/{text}"), false));
            }
            return nodes;
        }
        _menus[index] = _native[index] with { Children = [.. _native[index].Children ?? [], .. Parse(0, menu)] };
    }

    /// <summary>Puts <paramref name="node"/> into SketchUp's own <paramref name="menu"/> after the item labelled
    /// <paramref name="after"/>; call before <see cref="SetExtensionMenu"/> for that menu.</summary>
    public void InsertNative(string menu, string after, MenuNode node)
    {
        var index = _native.FindIndex(m => m.Label.Replace("&", "") == menu);
        var children = (_native[index].Children ?? []).ToList();
        children.Insert(children.FindIndex(c => c.Label.Replace("&", "") == after) + 1, node);
        _native[index] = _native[index] with { Children = children };
    }

    /// <summary>The menus as an indented tree, separators as "---".</summary>
    public string MenuText()
    {
        var sb = new System.Text.StringBuilder();
        void Walk(IEnumerable<MenuNode> nodes, int depth)
        {
            foreach (var n in nodes)
            {
                var off = n.Id is { } id && !Get(id).IsImplemented ? "  [off]" : "";
                sb.Append(' ', depth * 2).AppendLine(n.IsSeparator ? "---" : n.Label.Replace("&", "") + off);
                if (n.Children != null)
                    Walk(n.Children, depth + 1);
            }
        }
        Walk(_menus, 0);
        return sb.ToString();
    }

    /// <summary>Items replaced, when their menu opens, by a list (File › Recent File becomes the recent files); the item
    /// itself shows when the list is empty.</summary>
    public Dictionary<int, Func<IEnumerable<DynamicItem>>> DynamicItems { get; } = [];

    /// <summary>Submenus built entirely when they open (Edit › Items): each fills the menu and returns its actions by id.</summary>
    public Dictionary<string, Func<PopupMenu, Dictionary<int, Action>>> SubmenuBuilders { get; } = [];

    /// <summary>Submenus filled when they open (Camera › Edit Matched Photo lists the photo scenes), by label.</summary>
    public Dictionary<string, Func<IEnumerable<(string Label, Action Run)>>> DynamicMenus { get; } = [];

    public void Register(int id, Action execute, Func<bool>? isChecked = null, bool radio = false)
    {
        var cmd = Get(id);
        cmd.Execute = execute;
        cmd.IsChecked = isChecked;
        cmd.IsRadio = radio;
    }

    /// <summary>
    /// An extension's menu item, appended to a top-level menu as SketchUp's <c>UI.menu("Tools").add_item</c> does
    /// (after a separator, once per extension). <paramref name="submenu"/> puts it in a submenu of that menu;
    /// <paramref name="after"/> places it right after the item with that label instead; <paramref name="groupStart"/> puts a
    /// separator before it inside the submenu.
    /// </summary>
    public void AddToMenu(string menu, int id, string label, string description, string? submenu = null, bool separator = true, string? after = null, bool groupStart = false)
    {
        var index = _menus.FindIndex(m => m.Label.Replace("&", "") == menu);
        if (index < 0)
            return;
        var top = _menus[index];
        var children = (top.Children ?? []).ToList();
        var item = new MenuNode(label, id, null, false);
        if (submenu != null)
        {
            var at = children.FindIndex(c => c.Children != null && c.Label == submenu);
            if (at >= 0)
                children[at] = children[at] with { Children = groupStart ? [.. children[at].Children!, new MenuNode("", null, null, true), item] : [.. children[at].Children!, item] };
            else
            {
                if (separator)
                    children.Add(new MenuNode("", null, null, true));
                children.Add(new MenuNode(submenu, null, [item], false));
            }
        }
        else if (after != null && children.FindIndex(c => c.Label.Replace("&", "").Replace("...", "") == after) is var at and >= 0)
        {
            children.Insert(at + 1, item);
            if (groupStart)
                children.Insert(at + 1, new MenuNode("", null, null, true));
        }
        else
        {
            if (separator)
                children.Add(new MenuNode("", null, null, true));
            children.Add(item);
        }
        _menus[index] = top with { Children = children };
        var cmd = Get(id);
        cmd.Label = label;
        cmd.Description = description;
        cmd.MenuPath = submenu == null ? $"{menu}/{label}" : $"{menu}/{submenu}/{label}";
    }

    public bool Execute(int id)
    {
        if (!_commands.TryGetValue(id, out var cmd) || cmd.Execute == null)
            return false;
        cmd.Execute();
        return true;
    }

    private List<MenuNode> ParseMenus(JsonElement items, string path)
    {
        var list = new List<MenuNode>();
        foreach (var it in items.EnumerateArray())
        {
            if (it.TryGetProperty("separator", out _))
            {
                list.Add(new MenuNode("", null, null, true));
                continue;
            }
            var label = it.GetProperty("label").GetString() ?? "";
            var clean = label.Replace("&", "").Replace("...", "").Split('\t')[0];
            if (it.TryGetProperty("children", out var children))
                list.Add(new MenuNode(label, null, ParseMenus(children, path.Length == 0 ? clean : $"{path}/{clean}"), false));
            else
            {
                var id = it.GetProperty("id").GetInt32();
                list.Add(new MenuNode(label, id, null, false));
                var cmd = Get(id);
                if (cmd.Label.Length == 0)
                    cmd.Label = label;
                if (cmd.MenuPath.Length == 0)
                    cmd.MenuPath = path.Length == 0 ? clean : $"{path}/{clean}";
            }
        }
        return list;
    }

    /// <summary>Human-readable shortcut, e.g. "Ctrl+Shift+E".</summary>
    public static string ShortcutText(Key keys) => keys == Key.None ? "" : OS.GetKeycodeString(keys);

    /// <summary>Parses accelerator text such as "Ctrl+Shift+E", "PgDn", "Space" or "F1".</summary>
    public static Key ParseKeys(string text)
    {
        var result = Key.None;
        foreach (var part in text.Split('+'))
        {
            result |= part switch
            {
                "Ctrl" => (Key)KeyModifierMask.MaskCtrl,
                "Shift" => (Key)KeyModifierMask.MaskShift,
                "Alt" => (Key)KeyModifierMask.MaskAlt,
                "Space" => Key.Space,
                "Delete" => Key.Delete,
                "Insert" => Key.Insert,
                "Backspace" => Key.Backspace,
                "PgUp" => Key.Pageup,
                "PgDn" => Key.Pagedown,
                "Enter" => Key.Enter,
                "Esc" => Key.Escape,
                _ when part.Length > 1 && part[0] == 'F' && int.TryParse(part[1..], out var n) => Key.F1 + (n - 1),
                _ when part.Length == 1 && char.IsLetterOrDigit(part[0]) => (Key)char.ToUpperInvariant(part[0]),
                _ => Key.None,
            };
        }
        return result;
    }
}
